# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - master
      - feat/*
  paths:
    include:
      - 'service-a/*'

pool:
  name: Default
  vmImage: 'ubuntu-latest'
  environment: a

stages:
- stage: 'A'
  displayName: 'Deploy to the A environment'
  jobs:
  - deployment: Deploy
    pool:
      name: Default
      vmImage: 'ubuntu-20.04'
    environment: a
    variables:
    - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Hello from 'a'"